[package]
name = "yaml_database_schema_parser"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A YAML parser for database schema files"

[dependencies]
pest = "2.7.14"
pest_derive = "2.7.14"
anyhow = "1.0.93"
thiserror = "2.0.0"
